Fixed weird indentation in squash hook by using hard tabs

diff --git a/src/hooks/squashfs b/src/hooks/squashfs
--- a/src/hooks/squashfs
+++ b/src/hooks/squashfs
@@ -21,7 +21,7 @@ mount_handler_squashfs() {
 	local tmp device path imagepath imagedev_mountpoint tab real_imagedev_mountpoint
 	imagepath="/image/root.squashfs"
 	imagedev_mountpoint="/image_source"
-    tab="${1}/etc/fstab"
+	tab="${1}/etc/fstab"
 	case ${squashfs} in
 		http://* | https://* | ftp://* )
 			echo "Detected remote SquashFS source..."
@@ -130,22 +130,22 @@ mount_handler_squashfs() {
 			launch_interactive_shell
 		fi
 
-        if [[ mountpoint -q "${imagedev_mountpoint}" ]]; then
-            echo "Image source filesystem still mounted"
-            echo "Checking new root's fstab for final mount point image source"
-            if [ -f "$tab" ]; then
-                if real_imagedev_mountpoint=$(findmnt -snero target --tab-file="$tab" -S "$device"); then
-                    msg "Moving ${imagedev_mountpoint} to ${1}${real_imagedev_mountpoint}"
-                    mount --move "${imagedev_mountpoint}" "${1}${real_imagedev_mountpoint}"
+		if [[ mountpoint -q "${imagedev_mountpoint}" ]]; then
+			echo "Image source filesystem still mounted"
+			echo "Checking new root's fstab for final mount point image source"
+			if [ -f "$tab" ]; then
+				if real_imagedev_mountpoint=$(findmnt -snero target --tab-file="$tab" -S "$device"); then
+					msg "Moving ${imagedev_mountpoint} to ${1}${real_imagedev_mountpoint}"
+					mount --move "${imagedev_mountpoint}" "${1}${real_imagedev_mountpoint}"
 
-		            if [[ ! $? -eq 0 ]]; then
-			            err "Unable to move image source mount point..."
-                        echo "Check your fstab"
-                        msg "Continuing..."
-		            fi
-                fi
-            fi
-        fi
+					if [[ ! $? -eq 0 ]]; then
+						err "Unable to move image source mount point..."
+						echo "Check your fstab"
+						msg "Continuing..."
+					fi
+				fi
+			fi
+		fi
 
 	fi
 }
